export interface Proyectos{
    folio?:string
    nombreProyect:string
    contratista?:string
    division:string
    ciudad:string
    producto:string
    supervisorTelmex?:string
    supervisor:string
    fechaInicio:Date
    fechaTermino:Date
    duracion?:string
    transcurrido?:number
    documentos?:string
    costoAprox?:string
    obProyect?:string
    pepProyect?:string
    opProyect?:string
    oeiProyect?:string
    oeProyect?:string
    observacionProyect?:string
    status:string
    etapas:string
    usuario:string
    _id?:string
}